import {
  prefixObjectValues
} from '../../utils';

export const PREFIX = "@@SEARCH/";

let types = {
  INIT: "INIT",

  REQUEST_FILTERED_SERIES: "REQUEST_FILTERED_SERIES",
  RECEIVE_FILTERED_SERIES: "RECEIVE_FILTERED_SERIES",
  FAILURE_FILTERED_SERIES: "FAILURE_FILTERED_SERIES",

  QUERY_SERIES: "QUERY_SERIES",

  REQUEST_SAVE_SEEN: "REQUEST_SAVE_SEEN",
  RECEIVE_SAVE_SEEN: "RECEIVE_SAVE_SEEN",
  FAILURE_SAVE_SEEN: "FAILURE_SAVE_SEEN"
};

export default prefixObjectValues(types, PREFIX);
